version: '2'
services:
  web:
    build: .
    volumes:
      - .:/app
    expose:
      - "8080"
    depends_on:
      - lb
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
  # mongo-express:
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - 8081:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: 123456
#Probar con un ngnix
  lb:
    image: nginx
    volumes:
     - ./proxy.conf:/etc/nginx/nginx.conf
    ports:
     - "80:80"
    command: /bin/bash -c "envsubst < /etc/nginx/nginx.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    restart: always